server:
  port: 8090
  context-path: /duteliang
  session-timeout: 1800
logging:
  path: ./logs/spring_demo
  file: ./logs/spring_demo/demo.log
spring:
  datasource :
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost/test
    userName : root
    password : root
  thymeleaf :
    cache: false
    prefix: classpath:/page/
  resources:
    staticLocations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/, classpath:/public/,classpath:/page/static/