server:
  port: 8090
  context-path: /duteliang
  session:
    timeout: 1800
logging:
  path: ./logs/spring_demo
  file: ./logs/spring_demo/demo.log
spring:
  datasource :
    driverClassName : com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost/test
    userName : root
    password : root
  thymeleaf :
    cache: false
    prefix: classpath:/page/
  resources:
    staticLocations: classpath:/META-INF/resources/, classpath:/resources/,classpath:/static/, classpath:/public/,classpath:/page/static/
  activemq:
    user: activemq1
    password: activemq1
    broker-url: tcp://192.168.72.31:61616
    in-memory: true
    pool:
      enabled: true