server:
  port: 8090
  context-path: /
  session:
    timeout: 1800
logging:
  path: ./logs/spring_demo
  file: ./logs/spring_demo/demo.log
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
spring:
  datasource :
    url : jdbc:mysql://127.0.0.1:3307/test
    userName : root
    password : ROOT
sharding:
  jdbc:
    type: masterSlave