spring:
  redis:
#    cluster:
#      nodes:
#        - 127.0.0.1:7000
#        - 127.0.0.1:7001
#        - 127.0.0.1:7002
#        - 127.0.0.1:7003
#        - 127.0.0.1:7004
#        - 127.0.0.1:7005
#      max-redirects: 3
    host: 127.0.0.1
    port: 6379
    #    password:
    database: 0
    pool:
      max-active: 8
      min-idle: 0   # 最小空闲实例个数
      max-idle: 8   # 最多空闲实例个数
      max-wait: -1  #
  session:
    store-type: redis
